version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: oews_net
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin 
    ports:
      - "8080:80"
    depends_on:
      - db


volumes:
  pgdata:
  